/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import src.UberCar;

/**
 *
 * @author Trisha
 */
public class AddUberCar extends javax.swing.JFrame {

    transient ArrayList<UberCar> uberCars;
//ImageIcon carPicture = new ImageIcon("carowner1.png");
    transient String fileName;

    /**
     * Creates new form AddUberCar
     */
    public AddUberCar() {
        initComponents();
        uberCars = new ArrayList<UberCar>();
        fileName = "";
        populateArrayList();
    }

    public void populateArrayList() {
        try {
            FileInputStream file = new FileInputStream("UberCar.dat");
            ObjectInputStream ipfile = new ObjectInputStream(file);

            boolean eof = false;
            while (!eof) {
                try {
                    uberCars.add((UberCar) ipfile.readObject());
                } catch (EOFException eoe) {
                    eof = true;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
            ipfile.close();
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, ioe.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        engineNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberOfSeat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        licensePlate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modelNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        manufacturer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uberSerialNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        available = new java.awt.Checkbox();
        manufacturingYear = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1300, 600));

        jLabel1.setText("Engine Number :");

        jLabel2.setText("Number of seats :");

        jLabel3.setText("Maintenance Expiry Date :");

        jLabel4.setText("License Plate :");

        jLabel5.setText("Model Number :");

        modelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNumberActionPerformed(evt);
            }
        });

        jLabel7.setText("Manufacturer :");

        jLabel8.setText("Manufacturing Year :");

        jLabel9.setText("Uber Serial Number :");

        uberSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uberSerialNumberActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        available.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        available.setLabel("Available");

        manufacturingYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));

        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Enter Car Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfSeat)
                            .addComponent(engineNo))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(licensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(modelNumber))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uberSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(manufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton2))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(engineNo)
                    .addComponent(jLabel4)
                    .addComponent(licensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numberOfSeat)
                    .addComponent(jLabel5)
                    .addComponent(modelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(manufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(uberSerialNumber))
                                .addGap(198, 198, 198))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uberSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uberSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uberSerialNumberActionPerformed

    private void modelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNumberActionPerformed

    public void saveCarFile() {
        try {

            FileOutputStream file = new FileOutputStream("UberCar.dat");
            ObjectOutputStream otFile = new ObjectOutputStream(file);
            //JOptionPane.showMessageDialog(null, uberCars.size());
            for (int i = 0; i < uberCars.size(); i++) {
                otFile.writeObject(uberCars.get(i));
            }
            otFile.close();
            JOptionPane.showMessageDialog(null, "Data saved Successfully");
            this.dispose();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

        //Null and data type validation Start
        if (!(this.engineNo.getText().trim()).isEmpty()) {
            try {
                Integer.parseInt((this.engineNo.getText().trim()));
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(null, "Engine Number : Enter Numbers only");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Engine Number");
            return;
        }

        if ((this.licensePlate.getText().trim()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter License Plate");
            return;
        }

        if ((this.manufacturer.getText().trim()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Manufacturer");
            return;
        }

        if ((this.manufacturingYear.getSelectedItem().toString().trim()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Manufacture Year");
            return;
        }

        if (!(this.numberOfSeat.getText().trim()).isEmpty()) {
            try {
                Integer.parseInt((this.numberOfSeat.getText().trim()));
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(null, "Number of Seats : Enter Numbers only");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Number of Seats");
            return;
        }

        if (!(this.modelNumber.getText().trim()).isEmpty()) {
            try {
                Integer.parseInt((this.modelNumber.getText().trim()));
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(null, "Model Number : Enter Numbers only");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Model Number");
            return;
        }

        if ((this.jDateChooser1.getDate().toString()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter Maintenance Expiry Date");
            return;
        }

        if (!(this.uberSerialNumber.getText().trim()).isEmpty()) {
            try {
                Integer.parseInt((this.uberSerialNumber.getText().trim()));
            } catch (NumberFormatException n) {
                JOptionPane.showMessageDialog(null, "Uber Serial Number : Enter Numbers only");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter Uber Serial Number");
            return;
        }
        //Null and data type validation End
        String engineNo = this.engineNo.getText();
        String licenseplate = this.licensePlate.getText();
        String manufacturer = this.manufacturer.getText();
        String manufactureYear = this.manufacturingYear.getSelectedItem().toString();
        int numberOfSeat = Integer.parseInt(this.numberOfSeat.getText());
        int modelNumber = Integer.parseInt(this.modelNumber.getText());
        Date maintenanceExpDate = this.jDateChooser1.getDate();
        Boolean availability = this.available.getState();
        int uberSerialNo = Integer.parseInt(this.uberSerialNumber.getText());
        //Uniqueness Validation Start
        for (UberCar car : uberCars) {
            if (this.engineNo.getText().trim().equalsIgnoreCase(car.getEngineNo())) {
                JOptionPane.showMessageDialog(null, "Enter Unique Engine Number.");
                return;
            }

            if (this.licensePlate.getText().trim().equalsIgnoreCase(car.getLicenseplate())) {
                JOptionPane.showMessageDialog(null, "Enter Unique License Plate Details.");
                return;
            }

            if (uberSerialNo == (car.getUberSerialNumber())) {
                JOptionPane.showMessageDialog(null, "Enter Unique Uber Serial Number.");
                return;
            }
        }
        //Uniqueness Validation End

        UberCar uberCar = new UberCar(engineNo, licenseplate, manufacturer, manufactureYear, numberOfSeat, modelNumber, maintenanceExpDate, Boolean.TRUE, uberSerialNo, (System.currentTimeMillis()) + "", "");
        uberCars.add(uberCar);
        saveCarFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUberCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUberCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUberCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUberCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUberCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox available;
    private javax.swing.JTextField engineNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField licensePlate;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JComboBox<String> manufacturingYear;
    private javax.swing.JTextField modelNumber;
    private javax.swing.JTextField numberOfSeat;
    private javax.swing.JTextField uberSerialNumber;
    // End of variables declaration//GEN-END:variables
}
